### ISSUE TITLE
"Could not autoload puppet/type/mobileconfig"

### ISSUE THREAD

**Issue by eyemyth** [dayglojesus/managedmac#62]
Similar to https://github.com/dayglojesus/managedmac/issues/40

I'm just getting into puppet and have my master and a test client set up. I've added and used other modules with no issue. I installed and included managedmac in the node definition of my test node, and when I run `puppet agent -t` on the test node, I get:

```
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Could not retrieve fact='mac_battery_charge_percent', resolution='<anonymous>': invalid value for Float(): ""
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/mobileconfig: no such file to load -- puppet/managedmac/common on node mav-test-vm.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I'm running puppet 3.7.4 and facter 2.4.0 on both master and the test node. `gem list` reports CFPropertyList v 2.2.0 and sqlite3 1.3.7 on the client. I set `pluginsync = true`under `[agent]` in puppet.conf on both client and server. The client has stock Ruby: `ruby -V` reports `ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]`, `facter rubyversion` reports `2.0.0`, and `facter rubysitedir` reports `/Library/Ruby/Site/2.0.0`

**Comment by eyemyth** [comment]
Er, nevermind. I ran `puppet agent -t` on the master and now it works.

**Comment by dayglojesus** [comment]
You have a mac_battery_charge_percent fact? Nice.

Yeah, the real reason this happens is because of a problem with Puppet plugin sync -- not a managedmac issue perse, but one that affects the distribution of custom types/providers (which managedmac relies on (heavily)).

**Comment by eyemyth** [comment]
Yep, mac_battery_charge_percent comes from https://github.com/grahamgilbert/grahamgilbert-mac_facts

**Comment by dayglojesus** [comment]
I am going to raid Mr. Gilbert's repo some day. Uh, pardon?

**Comment by Ginja** [comment]
![Phrashing](http://31.media.tumblr.com/9e9f4a16f93e243554d65a7d7dafd4bd/tumblr_mn446i5Q4k1sqhz72o4_1280.png)
