### ISSUE TITLE
Doc update: file resource

### ISSUE THREAD

**Issue by clburlison** [dayglojesus/managedmac#63]
In puppet 4.0 we will get a compilation error if the mode for the file resource is not in quotes (see docs below). In later releases of 3.x we get a "Deprecated Resource" warning:

```puppet
Warning: Non-string values for the file mode property are deprecated. It must be a string, either a symbolic model like 'o+w,a+r' or an octal representation like '0644' or '755'.
```

Can we update the github pages and the ``manifests/files.pp`` file to add quotes around the mode?

Thanks,
Clayton
[puppetlabs docs](https://docs.puppetlabs.com/puppet/3.7/reference/deprecated_resource.html#in-puppet-40)

**Comment by dayglojesus** [comment]
Puppet 4. Bring it. Please send a pull req for the class patch and I will update the docs. Thanks for the bug report.

I bet this module is real "linty" against Puppet 4.
