### ISSUE TITLE
Error loading fact /var/lib/puppet/lib/facter/macaddress_primary.rb: cannot load such file -- cfpropertylist

### ISSUE THREAD

**Issue by dayglojesus** [dayglojesus/managedmac#90]
This fact is confined, but the gem reference is causing noisy errors on Linux hosts that don't have the gem installed.

The `require` directive (as well any other refs) need to go into a `begin` `rescue` clause that catches `LoadError`.

**Comment by helge000** [comment]
I modified my local version and just created a pull request ;)

**Comment by dayglojesus** [comment]
Fix is in develop. Ready for release 3.8.3.
