### ISSUE TITLE
Issues with El Capitan rootless

### ISSUE THREAD

**Issue by gregordickie** [dayglojesus/managedmac#96]
Hi, we are getting 'Operation not permitted' errors on El Capitan when enabling ssh and screen sharing:

`Error: Could not set 'true' on enable: Operation not permitted - /System/Library/LaunchDaemons/ssh.plist at 158:/etc/puppet/modules/managedmac/manifests/sshd.pp
Error: Could not set 'true' on enable: Operation not permitted - /System/Library/LaunchDaemons/ssh.plist at 158:/etc/puppet/modules/managedmac/manifests/sshd.pp
Wrapped exception:
Operation not permitted - /System/Library/LaunchDaemons/ssh.plist
Error: /Stage[main]/Managedmac::Sshd/Service[com.openssh.sshd]/enable: change from false to true failed: Could not set 'true' on enable: Operation not permitted - /System/Library/LaunchDaemons/ssh.plist at 158:/etc/puppet/modules/managedmac/manifests/sshd.pp
`

and 
`Error: Could not set 'true' on enable: Operation not permitted - /System/Library/LaunchDaemons/com.apple.screensharing.plist at 116:/etc/puppet/modules/managedmac/manifests/screensharing.pp
Error: Could not set 'true' on enable: Operation not permitted - /System/Library/LaunchDaemons/com.apple.screensharing.plist at 116:/etc/puppet/modules/managedmac/manifests/screensharing.pp
Wrapped exception:
Operation not permitted - /System/Library/LaunchDaemons/com.apple.screensharing.plist
Error: /Stage[main]/Managedmac::Screensharing/Service[com.apple.screensharing]/enable: change from false to true failed: Could not set 'true' on enable: Operation not permitted - /System/Library/LaunchDaemons/com.apple.screensharing.plist at 116:/etc/puppet/modules/managedmac/manifests/screensharing.pp
`

any ideas?

**Comment by dayglojesus** [comment]
Which Puppet version?

**Comment by gregordickie** [comment]
Sorry, I guess that's important. Server 3.8.6, client 3.8.1... oops, just tried client 3.8.6 and it works.

sorry for the noise.

Greg
